# Generated by Django 3.1.7 on 2021-03-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_auto_20210310_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.CharField(help_text='Link para foto do produto', max_length=200, null=True),
        ),
    ]
