# Generated by Django 3.1.7 on 2021-03-11 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_produto_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.CharField(help_text='Link para foto do produto', max_length=400, null=True),
        ),
    ]
