# Generated by Django 3.1.7 on 2021-03-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_auto_20210311_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(help_text='Categoria ao qual pertence o produto', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria'),
        ),
    ]
